# Site settings
author: Amanda Rowe
title: Learning Data Science
header-img: img/background-2462436_1920.jpg
email: rowe.as@gmail.com
copyright_name: Amanda Rowe
description: > # this means to ignore newlines until "baseurl:"
  Shifting from Math Teaching to Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  roweyerboat

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
